server:
  port: 8080

spring:
  config:
    import: env.properties
  application:
    api-prefix: /api/v1
    name: FurryFriendsHaven
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  main:
    banner-mode: off
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    cache: false

outbound:
  identity:
    client-id: "${GOOGLE_CLIENT_ID}"
    client-secret: "${GOOGLE_CLIENT_SECRET}"
    redirect-uri: "${GOOGLE_REDIRECT_URL}"

jwt:
  signerKey: "${SIGNING_KEY}"
  valid-duration: 1
  refreshable-duration: 120

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: ${VN_PAY_TMN_CODE}
    secretKey: ${VN_PAY_SECRET_KEY}
    returnUrl: http://localhost:3000/thanks
    version: 2.1.0
    command: pay
    orderType: other
